### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by Traktool** [illusivesoulworks/spectrelib#4]
Since the update made two hours ago, any mod running with this library crashes the server.

Fabric 1.20.1 0.14.23

**Comment by lospejos** [comment]
Do you have any logs of this crash? Please provide.

**Comment by Traktool** [comment]
I just restarted the server with Fabric 0.14.22 and it works.
And my host only provides logs for the current launch. Since it works now, I no longer have the logs of the crashes.

**Comment by lospejos** [comment]
A also downgraded version of Fabric Loader from 0.14.23 to 0.14.22 and my local Minecraft 1.20.2 started with mods containing spectrelib-fabric-0.13.13+1.20.1.jar (those failed on 0.14.23 Fabric Loader).

IMHO there is some incompatibility between 0.14.22 and 0.14.23 leading to mods crash.

**Comment by TheIllusiveC4** [comment]
Duplicate of https://github.com/illusivesoulworks/spectrelib/issues/3
