### ISSUE TITLE
Compatibility with 1.19.2 fabric 0.14.24

### ISSUE THREAD

**Issue by akai-hana** [illusivesoulworks/spectrelib#6]
Currently, the spectrelib version that the polymorph mod ships isn't compatible with fabric 0.14.24.
I'd love it if it received compatibility.

**Comment by TheIllusiveC4** [comment]
The current version of Polymorph for 1.19.2 is 0.46.5+1.19.2, which ships SpectreLib 0.12.6+1.19.2 that is compatible with Fabric Loader 0.14.23 and above. Please make sure your Polymorph is updated to that version. If you are still having issues, please provide the crash log or message denoting the incompatibility.
